package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseAuthCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthCode extends BaseAuthCode<AuthCode> {
	
}
