package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseDownloadLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DownloadLog extends BaseDownloadLog<DownloadLog> {
	
}
