package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseDownload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Download extends BaseDownload<Download> {
	
}
