package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseFavorite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Favorite extends BaseFavorite<Favorite> {
	
}
