package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	
}
