package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseFeedbackReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FeedbackReply extends BaseFeedbackReply<FeedbackReply> {
	
}
