package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseFeedback;
import com.zhu.jfinallearn.common.safe.JsoupFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {

    public static final int REPORT_BLOCK_NUM = 3 ;

    /**
     * 过滤 title content 字段的 html 标记，防止 XSS 攻击
     */
    protected void filter(int filterBy) {
        JsoupFilter.filterTitleAndContent(this);
    }


}
