package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	
}
