package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseNewsFeed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsFeed extends BaseNewsFeed<NewsFeed> {
	
}
