package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
	
}
