package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseReferMe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReferMe extends BaseReferMe<ReferMe> {
	
}
