package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseRemind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Remind extends BaseRemind<Remind> {
	
}
