package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	
}
