package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseShareReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShareReply extends BaseShareReply<ShareReply> {
	
}
