package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Share extends BaseShare<Share> {
    /**
     * 举报达到屏蔽的次数，达到这个数直接屏蔽帖子
     */
    public static final int REPORT_BLOCK_NUM = 3 ;


}
