package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Share extends BaseShare<Share> {
	
}
