package com.zhu.jfinallearn.common.model;

import com.zhu.jfinallearn.common.model.base.BaseTaskList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskList extends BaseTaskList<TaskList> {
	
}
